"""empty message

Revision ID: 17224bede8ca
Revises: ac62105ab03b
Create Date: 2021-11-01 14:13:24.065003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17224bede8ca'
down_revision = 'ac62105ab03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('URL', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('composer', sa.String(), nullable=False),
    sa.Column('performers', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audios')
    # ### end Alembic commands ###
